import { defineConfig } from 'vite';

/**
 * Front-end build for the Linear configuration page.
 *
 * Production: `npm run build` writes hashed assets plus a manifest to
 * `public/build` (manifest at `public/build/.vite/manifest.json`). The Blade
 * view resolves the entry through that manifest, so the output is committed.
 *
 * Development: `npm run dev` serves the entry from http://localhost:5173. The
 * Blade view switches to it when `LINEAR_VITE_DEV_URL` is set.
 */
const DEV_PORT = 5173;
const DEV_ORIGIN = `http://localhost:${DEV_PORT}`;

export default defineConfig({
  // Asset URLs inside the CSS/JS stay relative so the build works wherever
  // `php artisan vendor:publish --tag=linear-assets` puts it.
  base: './',
  // `public/` is the build output, so Vite must not treat it as a static dir.
  publicDir: false,
  build: {
    outDir: 'public/build',
    emptyOutDir: true,
    manifest: true,
    target: 'es2022',
    sourcemap: false,
    rollupOptions: {
      input: 'resources/js/main.ts',
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
      },
    },
  },
  server: {
    host: 'localhost',
    port: DEV_PORT,
    strictPort: true,
    // The page itself is served by Laravel (another origin), so allow it to
    // load modules and HMR from here.
    cors: true,
    // Makes URLs generated by Vite absolute and pointing at the dev server.
    origin: DEV_ORIGIN,
  },
});
